version: "3"

services:
  nginx:
    depends_on:
      - php
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ../:/var/www
    ports:
      - 8005:80

  php:
    container_name: "php-ed-it"
    build:
      context: ../
    depends_on:
      - db
    restart: always
    volumes:
      - ../:/var/www

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: test
